:- discontiguous
		fact/5,
    	ask/4.


% part 1 - execute in CLI `part1(Set,Count).`
part1(Set, Count) :- findall((X,Y), ask(X,Y,shiny,gold), Bag), list_to_set(Bag, Set), count(Set,Count).

count([],0).
count([_|Tail], N) :- count(Tail, N1), N is N1 + 1.


% Grammar/Rules
askSingle(X,Y,K,L) :- fact(X,Y,_,_,[_,K,L,_|_]).
askSingle(X,Y,K,L) :- fact(X,Y,_,_,[_,_O,_P,_|Rules]), iterate(K,L,Rules).

iterate(K,L, [_,K,L,_|_]).
iterate(K,L, [_,_K,_L,_|Rules]) :- iterate(K,L,Rules).

ask(X,Y,K,L) :- askSingle(X,Y,K,L).
ask(X,Y,K,L) :- askSingle(X,Y,L1,R1),  ask(L1,R1,K,L).



% Knowledge bases

fact(faded,yellow,bags,contain,[4,mirrored,fuchsia,bags,4,dotted,indigo,bags,3,faded,orange,bags,5,plaid,crimson,bags]).
fact(striped,olive,bags,contain,[4,dark,crimson,bags]).
fact(dotted,indigo,bags,contain,[4,faded,black,bags,4,clear,cyan,bags,5,vibrant,teal,bags]).
fact(plaid,crimson,bags,contain,[3,shiny,gold,bags,3,plaid,gray,bags]).
fact(muted,fuchsia,bags,contain,[3,shiny,bronze,bags]).
fact(plaid,gray,bags,contain,[no,other,bags]).
fact(dull,maroon,bags,contain,[2,posh,maroon,bags,3,wavy,aqua,bags,2,faded,white,bags,5,posh,bronze,bags]).
fact(dull,red,bags,contain,[3,striped,silver,bags,2,dark,tan,bags]).
fact(muted,lavender,bags,contain,[3,striped,red,bags]).
fact(shiny,lime,bags,contain,[1,dotted,olive,bag]).
fact(dim,violet,bags,contain,[5,faded,orange,bags,4,plaid,green,bags,1,faded,black,bag]).
fact(wavy,indigo,bags,contain,[4,bright,aqua,bags,2,dotted,orange,bags,2,vibrant,yellow,bags]).
fact(vibrant,purple,bags,contain,[3,plaid,indigo,bags,3,dark,gold,bags,3,striped,yellow,bags,3,light,tomato,bags]).
fact(plaid,plum,bags,contain,[1,faded,silver,bag]).
fact(striped,teal,bags,contain,[2,shiny,crimson,bags,1,dull,gray,bag,3,vibrant,teal,bags]).
fact(posh,crimson,bags,contain,[2,light,violet,bags]).
fact(pale,maroon,bags,contain,[2,wavy,maroon,bags,1,dotted,white,bag]).
fact(drab,cyan,bags,contain,[4,dim,violet,bags,5,pale,tan,bags,3,faded,black,bags]).
fact(bright,black,bags,contain,[2,faded,magenta,bags]).
fact(dotted,green,bags,contain,[3,muted,cyan,bags]).
fact(striped,chartreuse,bags,contain,[5,posh,silver,bags,5,wavy,violet,bags]).
fact(drab,olive,bags,contain,[5,dull,blue,bags]).
fact(drab,green,bags,contain,[2,vibrant,violet,bags,2,dim,violet,bags,2,light,brown,bags]).
fact(dark,violet,bags,contain,[5,drab,brown,bags,4,dim,chartreuse,bags,4,dark,salmon,bags]).
fact(faded,orange,bags,contain,[4,dull,lavender,bags]).
fact(dark,fuchsia,bags,contain,[2,clear,tomato,bags]).
fact(plaid,gold,bags,contain,[3,clear,tomato,bags]).
fact(muted,red,bags,contain,[1,muted,green,bag]).
fact(dark,coral,bags,contain,[5,muted,white,bags,3,mirrored,indigo,bags,1,shiny,blue,bag,2,drab,green,bags]).
fact(dark,chartreuse,bags,contain,[2,bright,teal,bags]).
fact(dim,silver,bags,contain,[4,shiny,white,bags,2,vibrant,plum,bags,3,clear,plum,bags]).
fact(clear,silver,bags,contain,[1,dull,gray,bag]).
fact(pale,gray,bags,contain,[no,other,bags]).
fact(plaid,chartreuse,bags,contain,[3,dull,brown,bags]).
fact(dotted,crimson,bags,contain,[3,pale,olive,bags,2,pale,black,bags]).
fact(dark,blue,bags,contain,[1,light,red,bag,5,striped,turquoise,bags]).
fact(dim,white,bags,contain,[5,bright,white,bags,4,light,magenta,bags,4,wavy,chartreuse,bags]).
fact(striped,magenta,bags,contain,[3,dull,coral,bags]).
fact(drab,bronze,bags,contain,[4,bright,red,bags]).
fact(light,gray,bags,contain,[1,mirrored,coral,bag]).
fact(wavy,brown,bags,contain,[4,clear,lime,bags,1,plaid,lavender,bag,1,faded,lavender,bag]).
fact(bright,violet,bags,contain,[5,clear,indigo,bags,1,plaid,indigo,bag,3,light,beige,bags]).
fact(drab,tan,bags,contain,[4,drab,chartreuse,bags]).
fact(shiny,teal,bags,contain,[1,bright,tan,bag]).
fact(dark,silver,bags,contain,[1,drab,orange,bag,1,striped,plum,bag,2,bright,gold,bags]).
fact(wavy,turquoise,bags,contain,[3,striped,gray,bags,1,dotted,lime,bag,4,pale,plum,bags,2,vibrant,orange,bags]).
fact(wavy,red,bags,contain,[1,dim,gold,bag,1,striped,turquoise,bag,1,bright,red,bag]).
fact(mirrored,yellow,bags,contain,[5,faded,cyan,bags,2,wavy,green,bags]).
fact(wavy,blue,bags,contain,[5,dark,violet,bags,4,vibrant,gray,bags]).
fact(mirrored,olive,bags,contain,[5,faded,orange,bags,2,posh,aqua,bags,3,dotted,silver,bags,2,striped,plum,bags]).
fact(faded,crimson,bags,contain,[3,striped,maroon,bags,4,pale,tomato,bags]).
fact(vibrant,olive,bags,contain,[2,wavy,yellow,bags,2,mirrored,orange,bags]).
fact(vibrant,fuchsia,bags,contain,[4,dim,yellow,bags,3,drab,tan,bags]).
fact(dotted,tan,bags,contain,[2,faded,fuchsia,bags,2,pale,turquoise,bags,4,mirrored,gray,bags]).
fact(mirrored,beige,bags,contain,[1,mirrored,olive,bag]).
fact(faded,turquoise,bags,contain,[5,dull,yellow,bags,5,clear,gray,bags,5,muted,lavender,bags]).
fact(wavy,violet,bags,contain,[5,dotted,gold,bags,5,dull,cyan,bags]).
fact(light,tan,bags,contain,[1,dull,salmon,bag,1,dull,bronze,bag,1,dull,tan,bag]).
fact(wavy,tan,bags,contain,[4,drab,black,bags]).
fact(muted,silver,bags,contain,[1,dark,lavender,bag,5,pale,tan,bags,2,clear,violet,bags,3,drab,coral,bags]).
fact(dull,blue,bags,contain,[5,muted,olive,bags,2,drab,salmon,bags,3,clear,red,bags]).
fact(bright,chartreuse,bags,contain,[5,dim,teal,bags]).
fact(posh,bronze,bags,contain,[3,plaid,black,bags,1,clear,lavender,bag,3,dim,chartreuse,bags,1,plaid,gray,bag]).
fact(striped,orange,bags,contain,[5,dull,turquoise,bags,2,dotted,olive,bags,5,bright,coral,bags,1,mirrored,aqua,bag]).
fact(posh,white,bags,contain,[4,dim,tomato,bags,5,light,salmon,bags]).
fact(faded,cyan,bags,contain,[2,plaid,crimson,bags,5,muted,green,bags,4,bright,olive,bags]).
fact(dark,red,bags,contain,[2,bright,blue,bags,5,faded,turquoise,bags,5,bright,black,bags]).
fact(pale,magenta,bags,contain,[4,drab,chartreuse,bags,2,light,tomato,bags,5,dull,lavender,bags]).
fact(posh,orange,bags,contain,[3,muted,gray,bags]).
fact(clear,tan,bags,contain,[2,dim,crimson,bags,3,light,olive,bags]).
fact(dark,green,bags,contain,[4,muted,maroon,bags,5,striped,gold,bags,2,drab,indigo,bags,2,dotted,silver,bags]).
fact(dim,blue,bags,contain,[5,wavy,coral,bags,4,shiny,chartreuse,bags,5,bright,teal,bags,2,drab,beige,bags]).
fact(dim,indigo,bags,contain,[2,dull,cyan,bags,3,dark,maroon,bags]).
fact(dotted,gold,bags,contain,[4,drab,tomato,bags,1,light,cyan,bag,2,pale,tan,bags,2,light,tomato,bags]).
fact(faded,gold,bags,contain,[2,drab,tan,bags,5,mirrored,chartreuse,bags,2,striped,gold,bags,3,bright,silver,bags]).
fact(muted,olive,bags,contain,[2,plaid,black,bags,3,shiny,gold,bags,4,vibrant,crimson,bags]).
fact(shiny,gray,bags,contain,[4,clear,violet,bags]).
fact(dim,teal,bags,contain,[no,other,bags]).
fact(drab,fuchsia,bags,contain,[4,dim,purple,bags,4,striped,beige,bags]).
fact(dark,cyan,bags,contain,[3,drab,salmon,bags]).
fact(clear,lavender,bags,contain,[2,dim,olive,bags,4,mirrored,gold,bags,4,striped,plum,bags]).
fact(posh,lime,bags,contain,[4,mirrored,teal,bags,3,wavy,chartreuse,bags,2,pale,cyan,bags,5,pale,indigo,bags]).
fact(vibrant,gold,bags,contain,[5,dim,chartreuse,bags,1,mirrored,red,bag,3,dark,lime,bags,4,shiny,silver,bags]).
fact(light,crimson,bags,contain,[3,muted,lavender,bags]).
fact(dark,lime,bags,contain,[1,faded,chartreuse,bag,3,shiny,crimson,bags,2,drab,aqua,bags]).
fact(dotted,beige,bags,contain,[1,faded,white,bag,5,vibrant,yellow,bags]).
fact(dim,chartreuse,bags,contain,[4,striped,lime,bags,2,faded,black,bags]).
fact(wavy,bronze,bags,contain,[5,muted,cyan,bags,3,light,yellow,bags,4,dotted,purple,bags]).
fact(striped,plum,bags,contain,[2,drab,black,bags,1,faded,silver,bag]).
fact(posh,chartreuse,bags,contain,[4,faded,blue,bags,2,vibrant,crimson,bags,4,dotted,purple,bags,4,posh,tan,bags]).
fact(vibrant,yellow,bags,contain,[4,dim,tan,bags,1,mirrored,fuchsia,bag]).
fact(pale,salmon,bags,contain,[2,dull,tan,bags,2,mirrored,crimson,bags,1,drab,chartreuse,bag,3,muted,crimson,bags]).
fact(drab,gray,bags,contain,[2,vibrant,coral,bags]).
fact(mirrored,teal,bags,contain,[5,vibrant,violet,bags]).
fact(striped,maroon,bags,contain,[2,dim,violet,bags,3,dotted,gold,bags,4,bright,olive,bags]).
fact(clear,turquoise,bags,contain,[4,plaid,green,bags]).
fact(vibrant,white,bags,contain,[5,dotted,beige,bags]).
fact(wavy,chartreuse,bags,contain,[1,faded,orange,bag,4,shiny,lavender,bags]).
fact(mirrored,gray,bags,contain,[1,clear,magenta,bag]).
fact(bright,aqua,bags,contain,[3,mirrored,gold,bags,5,shiny,magenta,bags,1,shiny,silver,bag,5,posh,tan,bags]).
fact(plaid,violet,bags,contain,[2,muted,olive,bags,2,dotted,chartreuse,bags,2,faded,magenta,bags,1,drab,cyan,bag]).
fact(plaid,olive,bags,contain,[3,wavy,lime,bags,2,faded,cyan,bags,2,posh,tan,bags]).
fact(bright,crimson,bags,contain,[4,clear,beige,bags,1,plaid,teal,bag,3,shiny,magenta,bags]).
fact(shiny,salmon,bags,contain,[3,light,silver,bags,3,faded,orange,bags,3,dim,tomato,bags,3,shiny,gold,bags]).
fact(mirrored,red,bags,contain,[5,shiny,black,bags]).
fact(shiny,fuchsia,bags,contain,[1,faded,yellow,bag,1,plaid,teal,bag]).
fact(wavy,tomato,bags,contain,[4,light,crimson,bags,3,clear,blue,bags]).
fact(clear,lime,bags,contain,[4,dark,gray,bags,5,drab,tomato,bags]).
fact(light,maroon,bags,contain,[3,dark,plum,bags,4,plaid,crimson,bags]).
fact(drab,yellow,bags,contain,[3,vibrant,aqua,bags,5,pale,red,bags]).
fact(mirrored,fuchsia,bags,contain,[3,pale,purple,bags,1,clear,yellow,bag,1,wavy,black,bag,4,pale,gray,bags]).
fact(clear,black,bags,contain,[1,plaid,lavender,bag,4,muted,indigo,bags]).
fact(drab,silver,bags,contain,[1,faded,green,bag,3,pale,black,bags]).
fact(clear,teal,bags,contain,[2,dotted,silver,bags]).
fact(plaid,indigo,bags,contain,[4,dotted,purple,bags]).
fact(striped,indigo,bags,contain,[1,mirrored,indigo,bag,4,faded,plum,bags,4,wavy,crimson,bags]).
fact(light,salmon,bags,contain,[no,other,bags]).
fact(dull,plum,bags,contain,[4,plaid,cyan,bags]).
fact(muted,tomato,bags,contain,[4,dark,violet,bags]).
fact(mirrored,orange,bags,contain,[no,other,bags]).
fact(striped,tomato,bags,contain,[5,dotted,chartreuse,bags,2,dark,white,bags]).
fact(dotted,magenta,bags,contain,[2,wavy,gold,bags,5,pale,gray,bags,2,bright,chartreuse,bags]).
fact(vibrant,blue,bags,contain,[3,dotted,cyan,bags,4,clear,gold,bags,2,dark,cyan,bags]).
fact(mirrored,crimson,bags,contain,[1,dim,salmon,bag,4,posh,aqua,bags]).
fact(shiny,turquoise,bags,contain,[2,striped,blue,bags,2,light,orange,bags,3,dim,fuchsia,bags,2,dark,olive,bags]).
fact(muted,gray,bags,contain,[3,dotted,yellow,bags,4,dim,orange,bags,3,clear,beige,bags,3,posh,tan,bags]).
fact(dim,bronze,bags,contain,[1,light,magenta,bag,4,shiny,purple,bags,1,light,red,bag]).
fact(dotted,olive,bags,contain,[2,dark,crimson,bags]).
fact(plaid,bronze,bags,contain,[4,bright,silver,bags,1,faded,lime,bag,3,striped,lime,bags,3,drab,coral,bags]).
fact(posh,blue,bags,contain,[2,clear,tomato,bags]).
fact(plaid,coral,bags,contain,[4,clear,turquoise,bags,1,plaid,brown,bag,1,drab,indigo,bag]).
fact(faded,magenta,bags,contain,[2,wavy,gray,bags,4,dark,gold,bags,4,shiny,white,bags,4,faded,black,bags]).
fact(light,brown,bags,contain,[3,striped,red,bags,4,faded,black,bags,5,vibrant,violet,bags]).
fact(dotted,turquoise,bags,contain,[2,mirrored,orange,bags]).
fact(pale,bronze,bags,contain,[2,mirrored,silver,bags,1,faded,cyan,bag]).
fact(dark,purple,bags,contain,[1,muted,lavender,bag,1,dull,yellow,bag,5,vibrant,tan,bags,1,dark,gold,bag]).
fact(plaid,white,bags,contain,[2,pale,turquoise,bags,4,clear,green,bags]).
fact(wavy,magenta,bags,contain,[3,shiny,blue,bags,1,dark,yellow,bag]).
fact(wavy,gold,bags,contain,[1,dotted,indigo,bag]).
fact(dull,lavender,bags,contain,[1,striped,plum,bag,5,pale,gray,bags]).
fact(shiny,silver,bags,contain,[5,shiny,lavender,bags,1,plaid,crimson,bag,1,wavy,black,bag]).
fact(clear,blue,bags,contain,[2,plaid,bronze,bags,1,shiny,purple,bag]).
fact(faded,chartreuse,bags,contain,[3,dull,bronze,bags]).
fact(pale,blue,bags,contain,[3,plaid,yellow,bags,1,pale,black,bag,4,clear,magenta,bags,3,mirrored,silver,bags]).
fact(vibrant,green,bags,contain,[4,bright,magenta,bags,4,dark,black,bags,5,wavy,chartreuse,bags]).
fact(drab,tomato,bags,contain,[3,drab,orange,bags,4,striped,coral,bags]).
fact(clear,cyan,bags,contain,[3,wavy,chartreuse,bags,1,light,salmon,bag,2,dim,purple,bags]).
fact(dim,magenta,bags,contain,[4,dim,turquoise,bags,1,clear,gray,bag,4,dim,lime,bags,3,mirrored,tomato,bags]).
fact(wavy,maroon,bags,contain,[5,pale,plum,bags,3,pale,black,bags,3,striped,red,bags,4,drab,salmon,bags]).
fact(posh,gold,bags,contain,[3,dim,chartreuse,bags,1,faded,blue,bag,4,mirrored,teal,bags]).
fact(muted,aqua,bags,contain,[2,faded,maroon,bags,1,mirrored,blue,bag,5,pale,crimson,bags]).
fact(muted,orange,bags,contain,[1,muted,olive,bag]).
fact(posh,tan,bags,contain,[4,muted,lavender,bags,2,plaid,crimson,bags,4,striped,lime,bags]).
fact(mirrored,indigo,bags,contain,[1,muted,olive,bag,2,vibrant,chartreuse,bags,4,light,cyan,bags]).
fact(wavy,crimson,bags,contain,[4,mirrored,violet,bags,2,vibrant,olive,bags,5,dull,lavender,bags,1,drab,cyan,bag]).
fact(dim,lavender,bags,contain,[4,light,salmon,bags,5,plaid,tomato,bags,4,drab,fuchsia,bags]).
fact(dotted,yellow,bags,contain,[4,vibrant,chartreuse,bags]).
fact(light,fuchsia,bags,contain,[2,wavy,red,bags,2,faded,lime,bags,1,pale,brown,bag,5,dotted,green,bags]).
fact(clear,beige,bags,contain,[5,drab,chartreuse,bags,4,dark,olive,bags,5,dim,gold,bags]).
fact(shiny,gold,bags,contain,[1,pale,turquoise,bag]).
fact(dim,tomato,bags,contain,[no,other,bags]).
fact(plaid,salmon,bags,contain,[1,striped,tan,bag,5,plaid,purple,bags,1,mirrored,crimson,bag]).
fact(dotted,lavender,bags,contain,[3,striped,teal,bags,1,vibrant,gray,bag]).
fact(light,olive,bags,contain,[3,posh,tomato,bags,5,dim,coral,bags,4,posh,white,bags,2,dark,turquoise,bags]).
fact(striped,silver,bags,contain,[1,clear,tomato,bag,1,drab,cyan,bag]).
fact(striped,lavender,bags,contain,[4,posh,chartreuse,bags,5,faded,coral,bags]).
fact(faded,beige,bags,contain,[5,muted,gold,bags,5,clear,gold,bags,2,posh,white,bags]).
fact(drab,indigo,bags,contain,[1,pale,magenta,bag]).
fact(light,blue,bags,contain,[2,light,chartreuse,bags,4,drab,black,bags,2,dull,bronze,bags]).
fact(dull,gold,bags,contain,[5,dark,blue,bags,2,bright,green,bags]).
fact(faded,bronze,bags,contain,[5,dim,olive,bags]).
fact(mirrored,lime,bags,contain,[5,pale,crimson,bags]).
fact(shiny,coral,bags,contain,[3,drab,green,bags,3,posh,white,bags,4,clear,gray,bags,3,muted,orange,bags]).
fact(clear,magenta,bags,contain,[3,plaid,olive,bags,4,plaid,indigo,bags,1,dull,blue,bag]).
fact(wavy,black,bags,contain,[3,clear,cyan,bags,3,dull,bronze,bags,2,wavy,chartreuse,bags]).
fact(pale,green,bags,contain,[2,mirrored,silver,bags,3,drab,blue,bags,5,drab,green,bags,4,pale,tomato,bags]).
fact(drab,violet,bags,contain,[1,drab,orange,bag,1,vibrant,indigo,bag,2,mirrored,chartreuse,bags]).
fact(light,chartreuse,bags,contain,[4,posh,white,bags,5,dull,bronze,bags,4,wavy,coral,bags]).
fact(dull,black,bags,contain,[4,muted,red,bags,4,faded,white,bags,5,plaid,tomato,bags,2,dark,blue,bags]).
fact(dark,gray,bags,contain,[2,bright,green,bags,5,light,blue,bags,3,light,tan,bags,2,shiny,gold,bags]).
fact(light,turquoise,bags,contain,[5,shiny,coral,bags,3,dull,brown,bags,3,striped,tan,bags,4,striped,silver,bags]).
fact(mirrored,magenta,bags,contain,[3,vibrant,silver,bags,4,vibrant,crimson,bags,4,shiny,coral,bags,1,shiny,indigo,bag]).
fact(dull,lime,bags,contain,[3,pale,turquoise,bags,2,bright,olive,bags]).
fact(mirrored,gold,bags,contain,[1,faded,silver,bag,4,pale,gray,bags]).
fact(clear,chartreuse,bags,contain,[4,dark,gray,bags,1,pale,lime,bag,1,plaid,fuchsia,bag]).
fact(dull,indigo,bags,contain,[4,posh,silver,bags]).
fact(dull,yellow,bags,contain,[3,wavy,lavender,bags,3,muted,maroon,bags]).
fact(bright,silver,bags,contain,[2,wavy,black,bags,1,dim,coral,bag]).
fact(clear,indigo,bags,contain,[1,posh,black,bag,4,muted,teal,bags,1,wavy,maroon,bag]).
fact(bright,brown,bags,contain,[3,shiny,cyan,bags,5,clear,green,bags,1,wavy,magenta,bag]).
fact(shiny,crimson,bags,contain,[1,faded,black,bag,2,vibrant,chartreuse,bags]).
fact(striped,white,bags,contain,[4,light,red,bags,3,dotted,cyan,bags]).
fact(pale,tomato,bags,contain,[1,posh,white,bag]).
fact(posh,salmon,bags,contain,[2,striped,white,bags,5,clear,purple,bags,5,bright,yellow,bags]).
fact(faded,blue,bags,contain,[5,drab,cyan,bags,1,plaid,crimson,bag,5,light,crimson,bags]).
fact(mirrored,black,bags,contain,[4,light,tan,bags,3,faded,blue,bags]).
fact(bright,red,bags,contain,[3,pale,magenta,bags,4,faded,chartreuse,bags]).
fact(drab,lavender,bags,contain,[5,dim,red,bags,4,wavy,black,bags,4,dull,cyan,bags,5,clear,gray,bags]).
fact(light,coral,bags,contain,[4,dark,lavender,bags,2,clear,orange,bags,2,dull,maroon,bags]).
fact(bright,plum,bags,contain,[1,shiny,blue,bag,5,striped,salmon,bags,2,plaid,olive,bags]).
fact(faded,tomato,bags,contain,[4,pale,turquoise,bags]).
fact(wavy,purple,bags,contain,[1,light,red,bag]).
fact(striped,crimson,bags,contain,[2,shiny,tan,bags,1,striped,salmon,bag,5,dotted,cyan,bags]).
fact(posh,olive,bags,contain,[3,vibrant,indigo,bags]).
fact(plaid,red,bags,contain,[4,dotted,violet,bags,1,plaid,black,bag,4,light,chartreuse,bags]).
fact(pale,aqua,bags,contain,[3,plaid,brown,bags]).
fact(dotted,silver,bags,contain,[5,striped,plum,bags]).
fact(plaid,magenta,bags,contain,[4,clear,lime,bags,1,muted,chartreuse,bag,1,dark,gray,bag]).
fact(vibrant,plum,bags,contain,[3,clear,yellow,bags,1,striped,salmon,bag]).
fact(faded,lime,bags,contain,[5,dull,plum,bags]).
fact(wavy,lavender,bags,contain,[3,dull,bronze,bags]).
fact(clear,olive,bags,contain,[5,pale,bronze,bags]).
fact(striped,cyan,bags,contain,[2,dotted,gray,bags]).
fact(drab,black,bags,contain,[no,other,bags]).
fact(posh,turquoise,bags,contain,[1,clear,teal,bag]).
fact(plaid,lime,bags,contain,[5,pale,gray,bags,5,shiny,black,bags,2,faded,tan,bags,4,clear,lavender,bags]).
fact(drab,maroon,bags,contain,[4,posh,maroon,bags,3,drab,lavender,bags,2,shiny,lavender,bags]).
fact(dull,beige,bags,contain,[3,mirrored,coral,bags,2,faded,fuchsia,bags,5,bright,fuchsia,bags]).
fact(dull,bronze,bags,contain,[2,mirrored,olive,bags]).
fact(striped,violet,bags,contain,[2,vibrant,orange,bags,3,muted,indigo,bags,5,light,plum,bags,2,dark,lavender,bags]).
fact(striped,fuchsia,bags,contain,[3,striped,salmon,bags,4,posh,brown,bags,1,posh,maroon,bag]).
fact(light,aqua,bags,contain,[4,clear,plum,bags,1,dull,orange,bag,5,wavy,magenta,bags,5,pale,chartreuse,bags]).
fact(wavy,lime,bags,contain,[1,mirrored,teal,bag,1,posh,tan,bag,5,clear,teal,bags,4,plaid,crimson,bags]).
fact(plaid,fuchsia,bags,contain,[4,dark,gold,bags,1,muted,red,bag,4,light,tomato,bags]).
fact(muted,white,bags,contain,[5,plaid,brown,bags,4,dotted,plum,bags,3,dim,crimson,bags,3,dim,aqua,bags]).
fact(pale,white,bags,contain,[4,mirrored,chartreuse,bags,2,bright,lavender,bags,5,striped,teal,bags]).
fact(vibrant,aqua,bags,contain,[3,faded,green,bags,4,muted,tomato,bags,2,clear,lavender,bags]).
fact(posh,red,bags,contain,[4,bright,chartreuse,bags,1,clear,red,bag]).
fact(striped,yellow,bags,contain,[2,faded,aqua,bags,3,light,fuchsia,bags,5,dotted,purple,bags,5,drab,coral,bags]).
fact(shiny,lavender,bags,contain,[2,faded,orange,bags]).
fact(dull,coral,bags,contain,[1,dull,tan,bag,2,dull,beige,bags,3,faded,maroon,bags,1,wavy,aqua,bag]).
fact(faded,violet,bags,contain,[5,clear,red,bags]).
fact(dark,turquoise,bags,contain,[3,light,chartreuse,bags]).
fact(plaid,silver,bags,contain,[2,drab,cyan,bags,1,dotted,gray,bag,4,pale,orange,bags]).
fact(pale,tan,bags,contain,[no,other,bags]).
fact(light,white,bags,contain,[2,shiny,lime,bags,5,dull,lavender,bags,4,plaid,white,bags]).
fact(dim,beige,bags,contain,[5,dotted,silver,bags,5,dark,gold,bags,1,muted,turquoise,bag,1,pale,olive,bag]).
fact(muted,crimson,bags,contain,[2,faded,silver,bags,2,dark,olive,bags]).
fact(shiny,tan,bags,contain,[2,dotted,salmon,bags]).
fact(dull,magenta,bags,contain,[3,drab,black,bags,5,dim,purple,bags,3,mirrored,bronze,bags]).
fact(dull,white,bags,contain,[1,clear,teal,bag,2,faded,violet,bags,4,dull,bronze,bags,2,dotted,gold,bags]).
fact(clear,green,bags,contain,[3,pale,crimson,bags]).
fact(dark,bronze,bags,contain,[4,shiny,cyan,bags,5,shiny,white,bags]).
fact(vibrant,red,bags,contain,[2,dark,tomato,bags,3,muted,crimson,bags]).
fact(striped,brown,bags,contain,[4,pale,yellow,bags]).
fact(light,bronze,bags,contain,[5,drab,silver,bags,5,wavy,purple,bags]).
fact(vibrant,tomato,bags,contain,[4,mirrored,orange,bags,3,faded,teal,bags]).
fact(bright,coral,bags,contain,[4,clear,maroon,bags,3,dim,chartreuse,bags]).
fact(shiny,green,bags,contain,[2,muted,crimson,bags,5,pale,tan,bags,3,drab,black,bags,3,striped,teal,bags]).
fact(mirrored,green,bags,contain,[2,light,black,bags,5,posh,purple,bags,1,posh,tan,bag,1,mirrored,orange,bag]).
fact(dull,tan,bags,contain,[3,bright,tomato,bags]).
fact(muted,indigo,bags,contain,[3,wavy,coral,bags]).
fact(shiny,blue,bags,contain,[1,wavy,black,bag,2,dull,maroon,bags]).
fact(posh,beige,bags,contain,[5,dim,crimson,bags,1,posh,white,bag,2,mirrored,teal,bags,2,vibrant,chartreuse,bags]).
fact(dim,plum,bags,contain,[2,vibrant,chartreuse,bags,2,posh,teal,bags,3,drab,white,bags]).
fact(vibrant,teal,bags,contain,[2,dim,tomato,bags,2,dim,teal,bags,4,drab,chartreuse,bags]).
fact(wavy,olive,bags,contain,[5,vibrant,gold,bags,2,drab,black,bags,2,shiny,lime,bags,2,light,coral,bags]).
fact(faded,white,bags,contain,[4,posh,cyan,bags,1,bright,red,bag,2,pale,olive,bags,3,plaid,olive,bags]).
fact(pale,indigo,bags,contain,[5,dim,crimson,bags,1,dim,tan,bag,5,plaid,green,bags]).
fact(pale,fuchsia,bags,contain,[4,light,purple,bags,4,clear,beige,bags,3,muted,teal,bags,3,light,blue,bags]).
fact(faded,gray,bags,contain,[1,clear,maroon,bag,2,dim,fuchsia,bags,5,bright,purple,bags,4,striped,turquoise,bags]).
fact(dark,lavender,bags,contain,[1,muted,lavender,bag,2,vibrant,crimson,bags,1,clear,yellow,bag]).
fact(light,magenta,bags,contain,[5,faded,coral,bags,3,muted,green,bags,4,mirrored,fuchsia,bags,1,clear,coral,bag]).
fact(plaid,cyan,bags,contain,[1,muted,crimson,bag]).
fact(dim,gold,bags,contain,[3,clear,cyan,bags,3,dim,tomato,bags,3,shiny,lavender,bags,2,vibrant,teal,bags]).
fact(bright,tomato,bags,contain,[1,striped,red,bag,1,vibrant,violet,bag,4,striped,turquoise,bags]).
fact(drab,teal,bags,contain,[2,posh,turquoise,bags,1,shiny,black,bag]).
fact(pale,olive,bags,contain,[2,shiny,gold,bags,3,posh,bronze,bags,4,bright,tomato,bags,2,bright,olive,bags]).
fact(pale,brown,bags,contain,[3,clear,tomato,bags]).
fact(dark,yellow,bags,contain,[3,light,brown,bags]).
fact(pale,black,bags,contain,[4,bright,silver,bags]).
fact(muted,brown,bags,contain,[2,light,crimson,bags,4,drab,chartreuse,bags,5,pale,turquoise,bags,4,posh,white,bags]).
fact(wavy,beige,bags,contain,[2,posh,maroon,bags,5,dark,turquoise,bags]).
fact(shiny,olive,bags,contain,[1,light,salmon,bag,2,light,crimson,bags]).
fact(dotted,teal,bags,contain,[4,pale,turquoise,bags]).
fact(clear,bronze,bags,contain,[1,dotted,tomato,bag,5,striped,maroon,bags,5,shiny,plum,bags,4,clear,lime,bags]).
fact(dim,lime,bags,contain,[3,dim,lavender,bags]).
fact(shiny,aqua,bags,contain,[2,clear,plum,bags,1,plaid,lavender,bag,2,faded,aqua,bags,1,dim,purple,bag]).
fact(vibrant,lime,bags,contain,[4,dotted,plum,bags,2,muted,gray,bags,1,posh,beige,bag]).
fact(muted,beige,bags,contain,[1,mirrored,lavender,bag,4,muted,plum,bags]).
fact(wavy,yellow,bags,contain,[4,posh,cyan,bags,5,dim,gold,bags,3,vibrant,violet,bags]).
fact(bright,purple,bags,contain,[1,bright,chartreuse,bag,5,posh,violet,bags,2,pale,purple,bags]).
fact(vibrant,violet,bags,contain,[2,wavy,coral,bags,2,pale,gray,bags]).
fact(faded,indigo,bags,contain,[5,muted,tomato,bags,2,dull,tomato,bags]).
fact(mirrored,brown,bags,contain,[1,shiny,white,bag,4,dotted,lavender,bags,3,striped,cyan,bags,5,clear,crimson,bags]).
fact(bright,beige,bags,contain,[2,bright,salmon,bags]).
fact(bright,gold,bags,contain,[4,plaid,crimson,bags]).
fact(drab,gold,bags,contain,[5,pale,tan,bags]).
fact(bright,orange,bags,contain,[1,vibrant,gold,bag]).
fact(shiny,brown,bags,contain,[4,plaid,lime,bags,4,dull,gray,bags,1,pale,tomato,bag]).
fact(striped,beige,bags,contain,[1,clear,yellow,bag,1,pale,magenta,bag,4,dull,bronze,bags,5,bright,fuchsia,bags]).
fact(clear,brown,bags,contain,[2,bright,salmon,bags,2,vibrant,turquoise,bags]).
fact(muted,turquoise,bags,contain,[5,dim,crimson,bags,1,drab,chartreuse,bag]).
fact(dark,crimson,bags,contain,[5,bright,tomato,bags]).
fact(clear,yellow,bags,contain,[2,dim,olive,bags]).
fact(bright,lime,bags,contain,[5,faded,gray,bags,4,dull,gold,bags,3,dark,salmon,bags,4,posh,lime,bags]).
fact(muted,coral,bags,contain,[3,posh,bronze,bags,3,striped,gold,bags]).
fact(dark,salmon,bags,contain,[2,vibrant,indigo,bags,5,posh,coral,bags,3,faded,silver,bags]).
fact(vibrant,orange,bags,contain,[4,dark,turquoise,bags,2,vibrant,lime,bags]).
fact(pale,violet,bags,contain,[1,shiny,brown,bag,2,dim,plum,bags,3,dull,crimson,bags,3,bright,orange,bags]).
fact(shiny,purple,bags,contain,[1,vibrant,lavender,bag,1,dotted,yellow,bag]).
fact(drab,orange,bags,contain,[3,faded,aqua,bags]).
fact(posh,brown,bags,contain,[3,pale,magenta,bags,4,faded,orange,bags,1,drab,chartreuse,bag]).
fact(shiny,bronze,bags,contain,[3,light,magenta,bags,3,drab,indigo,bags,5,vibrant,yellow,bags]).
fact(muted,teal,bags,contain,[3,dim,olive,bags]).
fact(bright,turquoise,bags,contain,[3,bright,chartreuse,bags,4,mirrored,tomato,bags]).
fact(muted,chartreuse,bags,contain,[4,faded,gray,bags,1,dull,salmon,bag,3,clear,beige,bags]).
fact(clear,white,bags,contain,[3,muted,maroon,bags]).
fact(posh,violet,bags,contain,[4,shiny,white,bags,1,dull,orange,bag]).
fact(dotted,brown,bags,contain,[4,muted,aqua,bags]).
fact(mirrored,plum,bags,contain,[5,clear,plum,bags,4,faded,tomato,bags]).
fact(drab,crimson,bags,contain,[1,pale,white,bag,4,dotted,maroon,bags,2,drab,beige,bags,5,drab,tan,bags]).
fact(plaid,black,bags,contain,[1,light,salmon,bag,3,mirrored,orange,bags,2,dim,purple,bags]).
fact(dim,orange,bags,contain,[4,wavy,black,bags,1,clear,red,bag]).
fact(faded,plum,bags,contain,[1,posh,violet,bag,1,pale,silver,bag,4,muted,magenta,bags]).
fact(vibrant,salmon,bags,contain,[2,dotted,red,bags,1,dull,maroon,bag,1,plaid,tomato,bag]).
fact(muted,cyan,bags,contain,[5,posh,aqua,bags,2,faded,silver,bags,2,striped,red,bags,4,dim,tomato,bags]).
fact(muted,salmon,bags,contain,[5,muted,teal,bags,3,striped,cyan,bags]).
fact(dim,cyan,bags,contain,[5,drab,brown,bags,4,muted,red,bags,1,wavy,coral,bag]).
fact(drab,blue,bags,contain,[4,faded,aqua,bags,2,pale,gray,bags]).
fact(dotted,lime,bags,contain,[3,light,olive,bags,2,light,tomato,bags,5,dull,gold,bags,2,dotted,gold,bags]).
fact(muted,violet,bags,contain,[4,wavy,coral,bags,4,pale,crimson,bags,1,dim,coral,bag,2,mirrored,coral,bags]).
fact(vibrant,maroon,bags,contain,[5,wavy,aqua,bags,4,muted,orange,bags,3,dull,tomato,bags]).
fact(light,tomato,bags,contain,[3,dim,tomato,bags,1,dim,purple,bag,2,plaid,gray,bags,3,striped,red,bags]).
fact(dotted,violet,bags,contain,[3,muted,green,bags,2,faded,silver,bags]).
fact(mirrored,coral,bags,contain,[5,drab,black,bags,2,vibrant,crimson,bags,2,mirrored,gold,bags]).
fact(muted,black,bags,contain,[3,mirrored,plum,bags,2,bright,olive,bags]).
fact(faded,olive,bags,contain,[1,vibrant,orange,bag,3,faded,gray,bags,3,shiny,green,bags,2,muted,lavender,bags]).
fact(clear,gold,bags,contain,[4,dim,purple,bags]).
fact(striped,lime,bags,contain,[2,pale,gray,bags,5,light,brown,bags,5,vibrant,violet,bags,4,bright,tomato,bags]).
fact(drab,coral,bags,contain,[2,pale,tan,bags,5,striped,teal,bags,1,drab,indigo,bag]).
fact(dotted,purple,bags,contain,[2,faded,chartreuse,bags,3,clear,beige,bags,4,striped,turquoise,bags]).
fact(light,gold,bags,contain,[2,dark,gold,bags,5,striped,salmon,bags]).
fact(faded,teal,bags,contain,[5,plaid,black,bags,5,dotted,crimson,bags,3,mirrored,magenta,bags]).
fact(dull,silver,bags,contain,[5,bright,yellow,bags,4,drab,aqua,bags,4,shiny,indigo,bags]).
fact(shiny,magenta,bags,contain,[5,pale,purple,bags]).
fact(dull,salmon,bags,contain,[2,shiny,black,bags,1,bright,tomato,bag]).
fact(posh,fuchsia,bags,contain,[1,pale,teal,bag,1,clear,orange,bag]).
fact(mirrored,lavender,bags,contain,[2,posh,brown,bags,3,light,tomato,bags,5,plaid,aqua,bags,2,vibrant,olive,bags]).
fact(posh,tomato,bags,contain,[2,drab,blue,bags]).
fact(faded,maroon,bags,contain,[2,dull,beige,bags,2,dark,gray,bags]).
fact(dotted,tomato,bags,contain,[4,mirrored,olive,bags,4,dull,gold,bags,2,dotted,silver,bags,4,wavy,maroon,bags]).
fact(muted,bronze,bags,contain,[2,dim,olive,bags,2,posh,lime,bags,3,drab,coral,bags,5,wavy,silver,bags]).
fact(wavy,aqua,bags,contain,[2,striped,lime,bags,4,wavy,lime,bags,2,dim,tan,bags,4,faded,cyan,bags]).
fact(dull,violet,bags,contain,[4,bright,gold,bags,2,dim,coral,bags]).
fact(posh,gray,bags,contain,[2,dull,bronze,bags,3,faded,blue,bags,4,posh,silver,bags]).
fact(striped,gold,bags,contain,[4,wavy,lavender,bags,2,muted,gray,bags,3,wavy,yellow,bags]).
fact(vibrant,black,bags,contain,[3,shiny,silver,bags,1,faded,yellow,bag]).
fact(dull,teal,bags,contain,[4,light,blue,bags,3,posh,lavender,bags]).
fact(muted,green,bags,contain,[4,vibrant,violet,bags]).
fact(plaid,green,bags,contain,[3,dim,purple,bags,4,dim,teal,bags,1,muted,cyan,bag]).
fact(plaid,blue,bags,contain,[2,light,purple,bags,4,dim,gold,bags,5,pale,black,bags,5,dim,lavender,bags]).
fact(vibrant,turquoise,bags,contain,[5,drab,orange,bags,4,dark,gold,bags]).
fact(muted,plum,bags,contain,[3,dull,aqua,bags,1,wavy,lime,bag,3,dark,green,bags]).
fact(bright,fuchsia,bags,contain,[5,wavy,gray,bags,1,dim,teal,bag,5,muted,cyan,bags]).
fact(clear,violet,bags,contain,[1,bright,salmon,bag]).
fact(dotted,chartreuse,bags,contain,[4,pale,plum,bags,2,bright,purple,bags]).
fact(vibrant,gray,bags,contain,[4,dark,turquoise,bags,5,faded,gold,bags,3,light,olive,bags]).
fact(dark,tan,bags,contain,[2,light,olive,bags,1,vibrant,fuchsia,bag,4,vibrant,blue,bags]).
fact(mirrored,violet,bags,contain,[2,muted,gray,bags]).
fact(mirrored,maroon,bags,contain,[5,mirrored,coral,bags,2,faded,lime,bags,3,dark,gray,bags]).
fact(dotted,black,bags,contain,[1,clear,violet,bag,2,wavy,chartreuse,bags,3,faded,silver,bags,2,plaid,gray,bags]).
fact(shiny,maroon,bags,contain,[3,wavy,turquoise,bags,2,dim,purple,bags,1,shiny,silver,bag,2,dim,cyan,bags]).
fact(dull,cyan,bags,contain,[3,mirrored,olive,bags]).
fact(drab,brown,bags,contain,[4,striped,lime,bags,2,bright,aqua,bags]).
fact(dim,crimson,bags,contain,[2,drab,black,bags,2,vibrant,teal,bags]).
fact(dim,brown,bags,contain,[2,mirrored,beige,bags]).
fact(vibrant,silver,bags,contain,[1,dark,gold,bag,4,vibrant,indigo,bags,5,dim,red,bags,3,light,blue,bags]).
fact(dull,olive,bags,contain,[2,clear,red,bags,1,vibrant,plum,bag]).
fact(faded,purple,bags,contain,[5,faded,olive,bags]).
fact(pale,yellow,bags,contain,[3,vibrant,teal,bags,3,shiny,violet,bags,2,dull,yellow,bags]).
fact(posh,black,bags,contain,[4,clear,beige,bags,4,striped,salmon,bags,4,wavy,lavender,bags]).
fact(dotted,cyan,bags,contain,[5,shiny,crimson,bags,5,dark,lavender,bags,5,faded,green,bags,3,dull,lime,bags]).
fact(mirrored,silver,bags,contain,[4,light,lime,bags,1,posh,tomato,bag]).
fact(pale,gold,bags,contain,[2,striped,teal,bags,3,wavy,chartreuse,bags,2,plaid,tomato,bags]).
fact(dotted,white,bags,contain,[2,muted,purple,bags,2,posh,white,bags,3,faded,plum,bags]).
fact(mirrored,tan,bags,contain,[2,clear,bronze,bags,2,clear,orange,bags,5,striped,gray,bags]).
fact(plaid,beige,bags,contain,[4,drab,turquoise,bags]).
fact(faded,red,bags,contain,[3,vibrant,yellow,bags,3,pale,brown,bags,4,dim,beige,bags,5,wavy,chartreuse,bags]).
fact(pale,coral,bags,contain,[3,clear,coral,bags]).
fact(dull,orange,bags,contain,[5,wavy,chartreuse,bags,5,plaid,cyan,bags]).
fact(dull,brown,bags,contain,[5,plaid,olive,bags,3,faded,chartreuse,bags,3,mirrored,crimson,bags]).
fact(mirrored,aqua,bags,contain,[5,faded,green,bags]).
fact(vibrant,tan,bags,contain,[1,dark,turquoise,bag,4,plaid,lime,bags]).
fact(faded,fuchsia,bags,contain,[4,clear,gray,bags,4,faded,silver,bags]).
fact(dim,purple,bags,contain,[5,dull,lavender,bags,4,faded,black,bags,1,muted,cyan,bag]).
fact(posh,purple,bags,contain,[1,wavy,turquoise,bag,1,drab,cyan,bag,2,dull,coral,bags,4,posh,yellow,bags]).
fact(drab,turquoise,bags,contain,[3,dull,black,bags,5,dotted,bronze,bags]).
fact(shiny,orange,bags,contain,[5,plaid,crimson,bags,4,dotted,coral,bags]).
fact(plaid,orange,bags,contain,[3,wavy,gray,bags,5,plaid,crimson,bags,2,striped,plum,bags,5,pale,beige,bags]).
fact(vibrant,bronze,bags,contain,[1,posh,turquoise,bag,3,plaid,turquoise,bags,1,dotted,crimson,bag]).
fact(clear,tomato,bags,contain,[5,mirrored,fuchsia,bags]).
fact(wavy,coral,bags,contain,[2,mirrored,orange,bags]).
fact(posh,coral,bags,contain,[5,dotted,salmon,bags]).
fact(bright,tan,bags,contain,[4,drab,gray,bags,4,vibrant,plum,bags]).
fact(dotted,gray,bags,contain,[1,dull,lime,bag,4,dotted,tomato,bags,4,faded,gold,bags]).
fact(pale,red,bags,contain,[2,mirrored,olive,bags,1,faded,blue,bag,1,dark,crimson,bag,3,striped,teal,bags]).
fact(striped,aqua,bags,contain,[2,drab,black,bags,5,dull,bronze,bags,3,pale,purple,bags,4,faded,silver,bags]).
fact(plaid,purple,bags,contain,[3,bright,salmon,bags,2,dim,beige,bags,3,faded,red,bags]).
fact(drab,purple,bags,contain,[4,dotted,black,bags,2,shiny,black,bags,1,light,plum,bag,1,dotted,gold,bag]).
fact(muted,purple,bags,contain,[3,pale,crimson,bags]).
fact(posh,silver,bags,contain,[4,bright,gold,bags,1,dim,coral,bag,2,drab,chartreuse,bags,1,dim,chartreuse,bag]).
fact(dark,black,bags,contain,[1,bright,green,bag,5,plaid,cyan,bags,4,dotted,purple,bags]).
fact(striped,coral,bags,contain,[3,shiny,lavender,bags]).
fact(shiny,yellow,bags,contain,[4,dim,tomato,bags,1,drab,white,bag]).
fact(bright,magenta,bags,contain,[2,muted,silver,bags,3,dull,bronze,bags,1,faded,blue,bag]).
fact(light,black,bags,contain,[4,posh,silver,bags]).
fact(pale,purple,bags,contain,[5,dull,lavender,bags,1,mirrored,orange,bag]).
fact(striped,salmon,bags,contain,[3,faded,chartreuse,bags,2,posh,white,bags,1,striped,lime,bag,3,drab,cyan,bags]).
fact(dull,fuchsia,bags,contain,[2,plaid,tomato,bags]).
fact(plaid,maroon,bags,contain,[5,dotted,red,bags,2,vibrant,magenta,bags,4,dotted,purple,bags]).
fact(posh,yellow,bags,contain,[2,wavy,beige,bags,5,light,yellow,bags,3,striped,gray,bags]).
fact(dull,turquoise,bags,contain,[1,drab,lavender,bag,4,faded,crimson,bags,2,drab,purple,bags]).
fact(wavy,silver,bags,contain,[5,dotted,cyan,bags,2,faded,blue,bags,2,faded,aqua,bags]).
fact(clear,orange,bags,contain,[5,posh,silver,bags,1,vibrant,teal,bag,1,pale,tomato,bag,3,dull,tomato,bags]).
fact(drab,chartreuse,bags,contain,[no,other,bags]).
fact(shiny,black,bags,contain,[5,dim,teal,bags,1,faded,silver,bag,2,posh,beige,bags,1,bright,olive,bag]).
fact(pale,teal,bags,contain,[2,dull,beige,bags]).
fact(drab,plum,bags,contain,[5,pale,beige,bags,2,wavy,maroon,bags]).
fact(vibrant,lavender,bags,contain,[4,wavy,yellow,bags]).
fact(dim,turquoise,bags,contain,[5,shiny,crimson,bags]).
fact(plaid,tan,bags,contain,[5,clear,purple,bags,2,light,indigo,bags,4,plaid,cyan,bags]).
fact(pale,silver,bags,contain,[1,pale,green,bag,4,striped,beige,bags]).
fact(mirrored,bronze,bags,contain,[1,drab,orange,bag,2,posh,lavender,bags,2,muted,gray,bags]).
fact(plaid,tomato,bags,contain,[4,striped,red,bags,3,bright,olive,bags]).
fact(bright,indigo,bags,contain,[4,dull,tan,bags]).
fact(light,violet,bags,contain,[5,faded,magenta,bags,5,drab,tomato,bags]).
fact(clear,aqua,bags,contain,[1,plaid,gray,bag]).
fact(drab,salmon,bags,contain,[5,faded,silver,bags,1,bright,tomato,bag,1,light,lime,bag]).
fact(light,teal,bags,contain,[5,wavy,brown,bags,2,muted,indigo,bags,2,pale,gold,bags]).
fact(drab,red,bags,contain,[2,shiny,chartreuse,bags,3,dim,yellow,bags,3,vibrant,teal,bags,3,mirrored,silver,bags]).
fact(bright,white,bags,contain,[5,dotted,tan,bags,4,drab,beige,bags,3,dim,indigo,bags,2,dotted,white,bags]).
fact(dotted,fuchsia,bags,contain,[3,faded,tomato,bags,1,dotted,lavender,bag]).
fact(dotted,aqua,bags,contain,[4,clear,plum,bags,4,faded,maroon,bags,1,posh,bronze,bag]).
fact(light,purple,bags,contain,[5,dotted,cyan,bags,4,posh,olive,bags,5,plaid,fuchsia,bags,3,striped,white,bags]).
fact(shiny,indigo,bags,contain,[2,mirrored,gold,bags,4,pale,magenta,bags,5,shiny,white,bags,4,posh,tan,bags]).
fact(pale,turquoise,bags,contain,[1,pale,tan,bag,4,striped,red,bags,1,bright,olive,bag]).
fact(plaid,aqua,bags,contain,[3,plaid,black,bags,3,dim,crimson,bags]).
fact(posh,cyan,bags,contain,[3,dim,tomato,bags,4,pale,crimson,bags,4,shiny,gold,bags]).
fact(mirrored,white,bags,contain,[2,faded,cyan,bags]).
fact(shiny,chartreuse,bags,contain,[3,muted,maroon,bags,2,dotted,teal,bags]).
fact(dim,green,bags,contain,[4,light,salmon,bags,1,muted,crimson,bag,2,striped,beige,bags]).
fact(striped,blue,bags,contain,[4,dark,bronze,bags,5,faded,plum,bags,3,bright,white,bags]).
fact(drab,lime,bags,contain,[4,dull,tomato,bags]).
fact(clear,purple,bags,contain,[2,drab,chartreuse,bags,4,clear,green,bags]).
fact(dotted,blue,bags,contain,[5,dim,purple,bags,3,dull,brown,bags]).
fact(vibrant,cyan,bags,contain,[2,drab,indigo,bags,4,faded,chartreuse,bags]).
fact(light,beige,bags,contain,[3,dark,orange,bags,3,vibrant,cyan,bags]).
fact(light,lavender,bags,contain,[1,muted,cyan,bag,5,faded,tan,bags]).
fact(dim,fuchsia,bags,contain,[2,pale,salmon,bags]).
fact(mirrored,purple,bags,contain,[2,clear,red,bags]).
fact(faded,brown,bags,contain,[1,clear,tan,bag,4,faded,crimson,bags]).
fact(muted,magenta,bags,contain,[5,pale,tomato,bags,3,muted,maroon,bags]).
fact(pale,beige,bags,contain,[5,dark,gold,bags,1,dull,beige,bag]).
fact(vibrant,brown,bags,contain,[2,striped,gold,bags,1,bright,gold,bag]).
fact(clear,coral,bags,contain,[4,pale,crimson,bags,1,dark,teal,bag,4,mirrored,coral,bags,4,striped,gold,bags]).
fact(striped,tan,bags,contain,[4,dim,violet,bags]).
fact(pale,chartreuse,bags,contain,[2,vibrant,blue,bags,5,dark,turquoise,bags,2,faded,olive,bags]).
fact(posh,plum,bags,contain,[1,plaid,aqua,bag]).
fact(striped,purple,bags,contain,[3,shiny,tomato,bags,5,posh,purple,bags]).
fact(dark,gold,bags,contain,[5,vibrant,crimson,bags,2,light,tomato,bags,3,light,salmon,bags,3,muted,brown,bags]).
fact(shiny,cyan,bags,contain,[1,vibrant,crimson,bag,5,drab,indigo,bags]).
fact(bright,yellow,bags,contain,[3,plaid,indigo,bags]).
fact(bright,blue,bags,contain,[5,mirrored,magenta,bags]).
fact(dotted,salmon,bags,contain,[5,vibrant,crimson,bags,2,posh,chartreuse,bags,5,wavy,gray,bags,4,pale,turquoise,bags]).
fact(dim,olive,bags,contain,[1,clear,cyan,bag]).
fact(striped,turquoise,bags,contain,[5,faded,silver,bags,3,pale,tan,bags,5,faded,orange,bags,2,bright,olive,bags]).
fact(vibrant,beige,bags,contain,[3,faded,yellow,bags,3,bright,green,bags,3,faded,bronze,bags,4,drab,fuchsia,bags]).
fact(clear,maroon,bags,contain,[1,vibrant,indigo,bag]).
fact(vibrant,coral,bags,contain,[2,mirrored,tomato,bags,5,dull,bronze,bags,1,vibrant,teal,bag,3,pale,salmon,bags]).
fact(dotted,orange,bags,contain,[2,plaid,green,bags,4,striped,violet,bags,4,bright,chartreuse,bags,4,dotted,plum,bags]).
fact(dull,tomato,bags,contain,[2,vibrant,crimson,bags]).
fact(wavy,teal,bags,contain,[1,bright,orange,bag]).
fact(dark,teal,bags,contain,[4,dim,tan,bags,4,striped,gray,bags,4,dim,red,bags,4,plaid,bronze,bags]).
fact(vibrant,indigo,bags,contain,[3,drab,coral,bags,2,plaid,green,bags,4,shiny,gold,bags,3,wavy,coral,bags]).
fact(striped,red,bags,contain,[4,faded,silver,bags,4,light,salmon,bags,3,drab,black,bags]).
fact(drab,aqua,bags,contain,[5,faded,black,bags]).
fact(wavy,plum,bags,contain,[4,posh,blue,bags,5,striped,olive,bags,3,shiny,violet,bags,4,bright,silver,bags]).
fact(posh,lavender,bags,contain,[3,wavy,silver,bags,1,drab,lavender,bag]).
fact(dotted,red,bags,contain,[5,drab,bronze,bags,5,plaid,gray,bags]).
fact(dark,orange,bags,contain,[4,mirrored,blue,bags,1,drab,black,bag]).
fact(bright,lavender,bags,contain,[4,shiny,magenta,bags,2,bright,tomato,bags,3,dim,salmon,bags,4,dim,purple,bags]).
fact(mirrored,chartreuse,bags,contain,[2,wavy,black,bags,4,dull,cyan,bags,5,striped,coral,bags]).
fact(mirrored,tomato,bags,contain,[5,clear,beige,bags]).
fact(wavy,fuchsia,bags,contain,[2,muted,silver,bags,2,shiny,gold,bags]).
fact(muted,lime,bags,contain,[2,striped,turquoise,bags,3,dim,tan,bags]).
fact(shiny,white,bags,contain,[4,mirrored,olive,bags]).
fact(posh,maroon,bags,contain,[3,vibrant,violet,bags,5,striped,turquoise,bags,2,dull,lavender,bags,4,faded,orange,bags]).
fact(faded,aqua,bags,contain,[2,faded,orange,bags,2,pale,magenta,bags,1,posh,white,bag]).
fact(mirrored,blue,bags,contain,[5,pale,purple,bags,2,light,red,bags,2,striped,teal,bags,4,shiny,crimson,bags]).
fact(dotted,plum,bags,contain,[1,light,chartreuse,bag,5,drab,tan,bags,3,pale,red,bags]).
fact(muted,tan,bags,contain,[3,drab,cyan,bags,2,posh,olive,bags,1,dim,tomato,bag]).
fact(shiny,tomato,bags,contain,[3,mirrored,cyan,bags,5,dim,yellow,bags]).
fact(pale,lavender,bags,contain,[2,dull,beige,bags]).
fact(pale,orange,bags,contain,[1,posh,gold,bag]).
fact(wavy,green,bags,contain,[4,posh,bronze,bags]).
fact(faded,lavender,bags,contain,[3,clear,gold,bags,4,mirrored,cyan,bags,4,faded,silver,bags,5,posh,chartreuse,bags]).
fact(posh,teal,bags,contain,[1,shiny,purple,bag,4,dotted,violet,bags,1,dotted,tomato,bag,5,dull,indigo,bags]).
fact(clear,crimson,bags,contain,[2,shiny,lavender,bags]).
fact(dim,black,bags,contain,[2,vibrant,coral,bags,2,drab,green,bags]).
fact(dull,crimson,bags,contain,[3,vibrant,orange,bags,2,drab,salmon,bags]).
fact(muted,gold,bags,contain,[3,posh,chartreuse,bags,4,striped,gold,bags,4,drab,brown,bags,2,dim,black,bags]).
fact(dull,chartreuse,bags,contain,[3,clear,fuchsia,bags]).
fact(light,orange,bags,contain,[5,clear,orange,bags,5,faded,bronze,bags,3,clear,crimson,bags]).
fact(dark,tomato,bags,contain,[5,dotted,chartreuse,bags,3,dull,gray,bags,5,muted,crimson,bags]).
fact(dark,brown,bags,contain,[3,posh,red,bags]).
fact(faded,green,bags,contain,[1,dark,white,bag]).
fact(dark,olive,bags,contain,[4,vibrant,teal,bags,3,pale,magenta,bags,4,pale,gray,bags]).
fact(striped,bronze,bags,contain,[3,striped,tan,bags,5,dark,gray,bags,4,vibrant,white,bags]).
fact(striped,black,bags,contain,[1,striped,turquoise,bag,1,vibrant,olive,bag,1,striped,salmon,bag]).
fact(clear,plum,bags,contain,[4,wavy,chartreuse,bags,1,pale,bronze,bag,2,striped,plum,bags]).
fact(faded,tan,bags,contain,[2,muted,cyan,bags,4,dim,salmon,bags,3,vibrant,crimson,bags,4,striped,plum,bags]).
fact(faded,silver,bags,contain,[no,other,bags]).
fact(light,silver,bags,contain,[4,muted,gray,bags,3,mirrored,crimson,bags,3,dull,tan,bags,2,drab,indigo,bags]).
fact(dim,aqua,bags,contain,[2,posh,tomato,bags,2,muted,coral,bags,5,wavy,gray,bags,3,dull,tan,bags]).
fact(vibrant,crimson,bags,contain,[1,shiny,lavender,bag,3,bright,tomato,bags]).
fact(dim,maroon,bags,contain,[4,light,olive,bags]).
fact(bright,maroon,bags,contain,[2,faded,tan,bags,5,pale,tomato,bags,5,dotted,purple,bags]).
fact(dim,gray,bags,contain,[1,muted,gold,bag,4,shiny,magenta,bags,2,wavy,salmon,bags,2,posh,violet,bags]).
fact(dim,coral,bags,contain,[3,striped,coral,bags,5,clear,gold,bags,3,wavy,chartreuse,bags]).
fact(posh,indigo,bags,contain,[3,dull,salmon,bags]).
fact(striped,green,bags,contain,[3,vibrant,crimson,bags,4,plaid,plum,bags,4,muted,brown,bags]).
fact(dull,purple,bags,contain,[3,drab,gold,bags,1,plaid,gray,bag,4,striped,silver,bags]).
fact(light,yellow,bags,contain,[3,pale,salmon,bags,5,dark,cyan,bags,3,dull,tomato,bags,3,mirrored,silver,bags]).
fact(shiny,red,bags,contain,[3,faded,gold,bags,1,light,salmon,bag,5,mirrored,turquoise,bags]).
fact(vibrant,magenta,bags,contain,[1,drab,tomato,bag,5,plaid,cyan,bags]).
fact(plaid,lavender,bags,contain,[1,dull,lavender,bag,5,vibrant,black,bags,2,muted,olive,bags,4,shiny,lavender,bags]).
fact(light,cyan,bags,contain,[1,bright,silver,bag]).
fact(dark,plum,bags,contain,[2,drab,salmon,bags,3,dull,violet,bags,3,posh,lime,bags]).
fact(dull,green,bags,contain,[4,bright,gold,bags,2,posh,gold,bags,2,striped,plum,bags]).
fact(wavy,salmon,bags,contain,[3,faded,gray,bags,5,dotted,cyan,bags,3,plaid,maroon,bags]).
fact(pale,lime,bags,contain,[1,shiny,purple,bag]).
fact(shiny,plum,bags,contain,[3,mirrored,magenta,bags,4,clear,violet,bags,5,dull,tomato,bags,5,dotted,violet,bags]).
fact(dim,red,bags,contain,[2,posh,white,bags,4,drab,cyan,bags,1,dark,yellow,bag,1,pale,purple,bag]).
fact(light,red,bags,contain,[3,dotted,indigo,bags,4,bright,tomato,bags,1,mirrored,olive,bag,4,pale,turquoise,bags]).
fact(dim,yellow,bags,contain,[5,faded,aqua,bags,2,shiny,purple,bags,1,plaid,bronze,bag]).
fact(drab,magenta,bags,contain,[4,dotted,coral,bags,3,plaid,lime,bags]).
fact(clear,gray,bags,contain,[5,plaid,green,bags,3,pale,purple,bags]).
fact(plaid,turquoise,bags,contain,[4,mirrored,crimson,bags,2,muted,lavender,bags,3,light,blue,bags,2,dull,blue,bags]).
fact(mirrored,turquoise,bags,contain,[5,muted,magenta,bags,4,light,red,bags]).
fact(pale,plum,bags,contain,[3,clear,beige,bags,5,striped,plum,bags,4,striped,lime,bags,2,striped,teal,bags]).
fact(vibrant,chartreuse,bags,contain,[2,drab,chartreuse,bags,2,striped,red,bags,4,dim,teal,bags]).
fact(striped,gray,bags,contain,[3,striped,red,bags,1,drab,green,bag]).
fact(muted,maroon,bags,contain,[4,clear,yellow,bags,1,dim,tan,bag,3,vibrant,cyan,bags,1,bright,tomato,bag]).
fact(posh,aqua,bags,contain,[3,faded,silver,bags,5,pale,tan,bags,2,striped,red,bags,3,light,salmon,bags]).
fact(dotted,bronze,bags,contain,[4,striped,gold,bags,5,dark,lime,bags,2,pale,magenta,bags,1,pale,salmon,bag]).
fact(dark,aqua,bags,contain,[4,dull,salmon,bags,2,striped,salmon,bags,5,clear,turquoise,bags]).
fact(plaid,brown,bags,contain,[4,posh,silver,bags]).
fact(bright,cyan,bags,contain,[2,posh,yellow,bags,5,posh,lavender,bags,4,shiny,cyan,bags]).
fact(dark,indigo,bags,contain,[5,pale,turquoise,bags,4,light,crimson,bags,2,dim,orange,bags]).
fact(muted,yellow,bags,contain,[3,light,coral,bags,1,vibrant,turquoise,bag,5,clear,magenta,bags,2,pale,olive,bags]).
fact(clear,fuchsia,bags,contain,[2,posh,silver,bags,1,striped,yellow,bag,3,striped,lime,bags]).
fact(bright,salmon,bags,contain,[2,vibrant,cyan,bags]).
fact(dotted,maroon,bags,contain,[2,posh,violet,bags]).
fact(shiny,violet,bags,contain,[3,dim,teal,bags]).
fact(plaid,teal,bags,contain,[2,drab,orange,bags,1,dim,violet,bag,1,bright,fuchsia,bag]).
fact(faded,salmon,bags,contain,[5,drab,orange,bags,3,clear,indigo,bags,1,plaid,cyan,bag]).
fact(shiny,beige,bags,contain,[5,bright,brown,bags,4,pale,brown,bags]).
fact(plaid,yellow,bags,contain,[3,vibrant,crimson,bags]).
fact(light,indigo,bags,contain,[4,vibrant,cyan,bags,2,dotted,purple,bags]).
fact(dull,aqua,bags,contain,[5,pale,tan,bags]).
fact(posh,green,bags,contain,[2,light,silver,bags,3,posh,lime,bags,2,vibrant,olive,bags]).
fact(dark,beige,bags,contain,[3,dotted,coral,bags,5,wavy,chartreuse,bags]).
fact(mirrored,salmon,bags,contain,[4,posh,blue,bags,5,posh,yellow,bags,4,posh,fuchsia,bags,3,drab,tomato,bags]).
fact(pale,crimson,bags,contain,[3,dim,tomato,bags,3,vibrant,teal,bags,5,dotted,silver,bags]).
fact(wavy,gray,bags,contain,[1,dim,olive,bag,4,plaid,green,bags]).
fact(bright,olive,bags,contain,[5,faded,orange,bags,1,plaid,black,bag,2,plaid,gray,bags,3,faded,silver,bags]).
fact(light,lime,bags,contain,[5,dull,lavender,bags,2,posh,aqua,bags,4,dull,aqua,bags]).
fact(dim,salmon,bags,contain,[3,muted,lavender,bags,1,light,lime,bag]).
fact(dark,white,bags,contain,[1,posh,aqua,bag,3,wavy,black,bags]).
fact(posh,magenta,bags,contain,[5,striped,silver,bags,3,wavy,bronze,bags,3,faded,beige,bags]).
fact(mirrored,cyan,bags,contain,[5,light,brown,bags,1,muted,cyan,bag,4,posh,silver,bags]).
fact(dark,magenta,bags,contain,[2,muted,indigo,bags,2,muted,coral,bags]).
fact(clear,salmon,bags,contain,[3,pale,chartreuse,bags]).
fact(dim,tan,bags,contain,[2,pale,crimson,bags]).
fact(bright,gray,bags,contain,[3,mirrored,fuchsia,bags]).
fact(bright,green,bags,contain,[5,plaid,crimson,bags,3,striped,turquoise,bags]).
fact(faded,black,bags,contain,[1,striped,red,bag,1,dim,teal,bag,5,faded,silver,bags,3,striped,plum,bags]).
fact(wavy,orange,bags,contain,[1,dark,white,bag]).
fact(wavy,cyan,bags,contain,[5,light,olive,bags]).
fact(muted,blue,bags,contain,[5,wavy,maroon,bags,1,light,tomato,bag]).
fact(light,green,bags,contain,[1,shiny,teal,bag,5,bright,lime,bags,4,drab,white,bags,5,posh,aqua,bags]).
fact(drab,white,bags,contain,[4,posh,silver,bags,4,mirrored,crimson,bags]).
fact(bright,teal,bags,contain,[5,dotted,purple,bags,1,faded,yellow,bag,4,shiny,coral,bags]).
fact(light,plum,bags,contain,[3,pale,cyan,bags,5,faded,tan,bags]).
fact(faded,coral,bags,contain,[4,dull,gray,bags]).
fact(dotted,coral,bags,contain,[2,posh,bronze,bags,5,posh,aqua,bags,2,mirrored,violet,bags]).
fact(pale,cyan,bags,contain,[2,mirrored,orange,bags,2,dim,tomato,bags]).
fact(drab,beige,bags,contain,[4,bright,aqua,bags,2,mirrored,tomato,bags,2,plaid,turquoise,bags,1,wavy,chartreuse,bag]).
fact(dark,maroon,bags,contain,[1,dull,gray,bag,2,mirrored,olive,bags,1,light,olive,bag,1,shiny,fuchsia,bag]).
fact(wavy,white,bags,contain,[4,dull,lavender,bags]).
fact(dull,gray,bags,contain,[5,plaid,black,bags,3,light,lime,bags,2,wavy,chartreuse,bags,5,dim,tomato,bags]).
fact(clear,red,bags,contain,[5,light,crimson,bags,3,faded,chartreuse,bags,4,clear,teal,bags,4,mirrored,blue,bags]).
fact(bright,bronze,bags,contain,[1,clear,magenta,bag,2,clear,gray,bags,2,dull,coral,bags,5,vibrant,gray,bags]).
